version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/spotify
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
